apiVersion: v1
data:
  index.html: |
    <h1>Header is head</h1>
    <p>This is the webpage.</p>
    <p><img src="https://t4.ftcdn.net/jpg/06/12/22/27/240_F_612222711_H1PrYUOd9DgFiFTvmHXFM5TiZOmMjEqf.jpg" alt="hatten är röd" />
    </p>
kind: ConfigMap
metadata:
  name: webb-page
